# Generated by Django 4.2.2 on 2023-07-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='owner',
        ),
    ]
