# Generated by Django 4.2.2 on 2023-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_id_character_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
