# Generated by Django 4.2.2 on 2023-07-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_character_age_character_character_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
