# Generated by Django 4.2.2 on 2023-07-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
