# Generated by Django 4.2.2 on 2023-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_character_weapon_alter_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
